// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5CDP9MgqbRapi7mxENKQG
// Component: TpXp-HtNY_R
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: 0jfYEX-SfGn8K/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent
import BidButton from "../../BidButton"; // plasmic-import: TW0Ca_Ns9A2yO/component

import { useScreenVariants as useScreenVariantsi1EpI54Sd5XS4R } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: i1epI54SD5xS4r/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_nft_deep_wire.module.css"; // plasmic-import: j5CDP9MgqbRapi7mxENKQG/projectcss
import sty from "./PlasmicShades.module.css"; // plasmic-import: TpXp-HtNY_R/css

import SearchsvgIcon from "./icons/PlasmicIcon__Searchsvg"; // plasmic-import: awgxW5ZUPDKTds/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: SpSM8I8Z8pYH6F/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: GDo5sayAt37nOm/icon
import captureDecran20220525A200826PngXUdItNoqUxIjj4 from "./images/captureDecran20220525A200826Png.png"; // plasmic-import: xUdITNoqUxIjj4/picture

export type PlasmicShades__VariantMembers = {};

export type PlasmicShades__VariantsArgs = {};
type VariantPropType = keyof PlasmicShades__VariantsArgs;
export const PlasmicShades__VariantProps = new Array<VariantPropType>();

export type PlasmicShades__ArgsType = {};
type ArgPropType = keyof PlasmicShades__ArgsType;
export const PlasmicShades__ArgProps = new Array<ArgPropType>();

export type PlasmicShades__OverridesType = {
  root?: p.Flex<"div">;
  header2?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  h5?: p.Flex<"h5">;
  textInput?: p.Flex<typeof TextInput>;
  bidButton?: p.Flex<typeof BidButton>;
  footer?: p.Flex<"div">;
  textbox?: p.Flex<typeof TextInput>;
};

export interface DefaultShadesProps {
  className?: string;
}

function PlasmicShades__RenderFunc(props: {
  variants: PlasmicShades__VariantsArgs;
  args: PlasmicShades__ArgsType;
  overrides: PlasmicShades__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsi1EpI54Sd5XS4R()
  });

  return (
    <React.Fragment>
      {}

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"header2"}
            data-plasmic-override={overrides.header2}
            className={classNames(projectcss.all, sty.header2)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__kX0R)}>
              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__dsT7K
                )}
                href={`/`}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"NDW"}
                  </span>
                </React.Fragment>
              </a>
            </div>

            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__rldhw)}>
                <a
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__hNaa0
                  )}
                  href={`/`}
                >
                  {"About"}
                </a>

                <a
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___6I8Pb
                  )}
                  href={`/`}
                >
                  {"Artists"}
                </a>

                <a
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__eTzzq
                  )}
                  href={`/`}
                >
                  {"Vision"}
                </a>

                <a
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__wekGs
                  )}
                  href={`/`}
                >
                  {"Login"}
                </a>
              </div>
            ) : null}
          </div>

          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
          ) ? (
            <div className={classNames(projectcss.all, sty.freeBox__cu2XM)}>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#FFFFFF" }}
                    >
                      {"Collection #1"}
                    </span>
                  </React.Fragment>
                ) : (
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#FFFFFF" }}
                    >
                      {"Exclusive shades"}
                    </span>
                  </React.Fragment>
                )}
              </h1>

              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__hUzeJ
                )}
                href={`/nft`}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__szvi6)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: captureDecran20220525A200826PngXUdItNoqUxIjj4,
                    fullWidth: 1232,
                    fullHeight: 1172,
                    aspectRatio: undefined
                  }}
                />
              </a>

              <h4
                className={classNames(
                  projectcss.all,
                  projectcss.h4,
                  projectcss.__wab_text,
                  sty.h4__g0Rcj
                )}
              >
                {"by Jean-Michel Plastic"}
              </h4>

              <h5
                data-plasmic-name={"h5"}
                data-plasmic-override={overrides.h5}
                className={classNames(
                  projectcss.all,
                  projectcss.h5,
                  projectcss.__wab_text,
                  sty.h5
                )}
              >
                {
                  "There will always be some text here. There will always be some text here. There will always be some text here. There will always be some text here. There will always be some text here. There will always be some text here. There will always be some text here. There will always be some text here. There will always be some text here. There will always be some text here. There will always be some text here. There will always be some text here. There will always be some text here. "
                }
              </h5>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lYqe9
                )}
              >
                {"00:00:00:08"}
              </div>

              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__cAHhb)}>
                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hxqZx)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mI3Bi
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {"4,230"}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {" "}
                          </span>
                          <React.Fragment>{"MATIC"}</React.Fragment>
                        </React.Fragment>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__okggQ
                        )}
                      >
                        {"Current highest bid "}
                      </div>
                    </div>
                  ) : null}
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__tFyfB)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"38.79%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"100%" as const}
                      loading={"lazy" as const}
                      src={{
                        src: captureDecran20220525A200826PngXUdItNoqUxIjj4,
                        fullWidth: 1232,
                        fullHeight: 1172,
                        aspectRatio: undefined
                      }}
                    />
                  ) : null}
                </div>
              ) : null}

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__t4WUn
                )}
              >
                {"(0 USD eq.)"}
              </div>

              <TextInput
                data-plasmic-name={"textInput"}
                data-plasmic-override={overrides.textInput}
                className={classNames("__wab_instance", sty.textInput)}
                color={"dark" as const}
                placeholder={"Your offer" as const}
              />

              <Reveal
                className={classNames("__wab_instance", sty.reveal__ov3Iz)}
                duration={3000 as const}
                effect={"fade" as const}
                triggerOnce={true}
              >
                <BidButton
                  data-plasmic-name={"bidButton"}
                  data-plasmic-override={overrides.bidButton}
                  className={classNames("__wab_instance", sty.bidButton)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jSnuq
                    )}
                  >
                    {"Bid"}
                  </div>
                </BidButton>
              </Reveal>

              <Reveal
                className={classNames("__wab_instance", sty.reveal__kxnmc)}
                effect={"flip" as const}
                triggerOnce={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xLhKs
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"You're currently the highest bidder "}
                    </span>
                    <React.Fragment>{"✅"}</React.Fragment>
                  </React.Fragment>
                </div>
              </Reveal>

              <h4
                className={classNames(
                  projectcss.all,
                  projectcss.h4,
                  projectcss.__wab_text,
                  sty.h4__gBk7R
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#FFFFFF" }}
                  >
                    {"Previous bids"}
                  </span>
                </React.Fragment>
              </h4>

              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__zjgie
                )}
                href={
                  "https://etherscan.io/tx/0x6c74bca6ad4f417ffaa892f0d20b055b2f915a83d5c47a1ed736686aac65e0e8" as const
                }
                target={"_blank" as const}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#FFFFFF" }}
                  >
                    {
                      "May-27-2022 04:35:28 PM +UTC                                                                                                   3,600 MATIC"
                    }
                  </span>
                </React.Fragment>
              </a>

              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__nNrlw
                )}
                href={
                  "https://etherscan.io/tx/0x6c74bca6ad4f417ffaa892f0d20b055b2f915a83d5c47a1ed736686aac65e0e8" as const
                }
                target={"_blank" as const}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#FFFFFF" }}
                  >
                    {
                      "May-27-2022 04:35:28 PM +UTC                                                                                                   3,500 MATIC"
                    }
                  </span>
                </React.Fragment>
              </a>

              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link___5T54M
                )}
                href={
                  "https://etherscan.io/tx/0x6c74bca6ad4f417ffaa892f0d20b055b2f915a83d5c47a1ed736686aac65e0e8" as const
                }
                target={"_blank" as const}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#FFFFFF" }}
                  >
                    {
                      "May-27-2022 04:35:28 PM +UTC                                                                                                   2,000 MATIC"
                    }
                  </span>
                </React.Fragment>
              </a>

              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link___0S7T9
                )}
                href={
                  "https://etherscan.io/tx/0x6c74bca6ad4f417ffaa892f0d20b055b2f915a83d5c47a1ed736686aac65e0e8" as const
                }
                target={"_blank" as const}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#FFFFFF" }}
                  >
                    {
                      "May-27-2022 04:35:28 PM +UTC                                                                                                   1,000 MATIC"
                    }
                  </span>
                </React.Fragment>
              </a>
            </div>
          ) : null}

          <div
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__dr3Iy)}>
              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__apk6F
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "NFT Deep Wire\nAll rights reserved © 2022"
                  : "NFT Deep Wire | All rights reserved © 2022"}
              </a>
            </div>

            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__v6Ia3)}>
                <a
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___5Lmi
                  )}
                  href={`/`}
                >
                  {"Terms & conditions"}
                </a>

                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : false
                ) ? (
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__a7I8H
                    )}
                  >
                    {"Contact us"}
                  </a>
                ) : null}
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header2",
    "h1",
    "h5",
    "textInput",
    "textbox",
    "bidButton",
    "footer"
  ],
  header2: ["header2"],
  h1: ["h1"],
  h5: ["h5"],
  textInput: ["textInput", "textbox"],
  bidButton: ["bidButton"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header2: "div";
  h1: "h1";
  h5: "h5";
  textInput: typeof TextInput;
  bidButton: typeof BidButton;
  footer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicShades__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicShades__VariantsArgs;
    args?: PlasmicShades__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicShades__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicShades__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicShades__ArgProps,
          internalVariantPropNames: PlasmicShades__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicShades__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicShades";
  } else {
    func.displayName = `PlasmicShades.${nodeName}`;
  }
  return func;
}

export const PlasmicShades = Object.assign(
  // Top-level PlasmicShades renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header2: makeNodeComponent("header2"),
    h1: makeNodeComponent("h1"),
    h5: makeNodeComponent("h5"),
    textInput: makeNodeComponent("textInput"),
    bidButton: makeNodeComponent("bidButton"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicShades
    internalVariantProps: PlasmicShades__VariantProps,
    internalArgProps: PlasmicShades__ArgProps
  }
);

export default PlasmicShades;
/* prettier-ignore-end */
